### ISSUE TITLE
1.29 compatibility

### ISSUE THREAD

**Issue by vanjad777** [WulfMarius/Show-Map-Location#5]
Hi,

I'm unable to load the mod (version 2.0) in TLD 1.29 (Apr 10). 
UModTLD and RememberBreakDownItem are both functional. I also noticed my game stopped writing output_log.txt which otherwise I would have attached it here.

Are you aware of any issues with 1.29?

Thank,
Vanja

**Comment by WulfMarius** [comment]
Hi,

I'm not aware of any issues with v1.29.
I just tested Show-Map-Location V2.0.0 with v1.29 and it worked as expected.

The location of the output_log.txt has changed to %USERPROFILE%\AppData\LocalLow\Hinterland\tld\output_log.txt (someone mentioned this was by mistake and it might revert back in the next version).

You should find some output in that file and maybe that already explains your problem.
If not, feel free to paste the file and I'll take a look.

**Comment by vanjad777** [comment]
Hi,

Thanks for the quick reply.

Unfortunately my game doesn't create the output_log.txt file in the new or old (tld_Data) location so I'm inclined to think the whole issue has something to do with the game itself, not the addon.
Once I fix that and if I'll still have issues, I'll reach out.

In any case, thanks for your help!

Br,
Vanja
