### ISSUE TITLE
No mods working

### ISSUE THREAD

**Issue by hozz1235** [WulfMarius/Show-Map-Location#6]
Hey Wulf.  #1 thanks for all the GREAT Long Dark mods!  I've updated all available mods to 1.44 but none of them seem to be working anymore.  I use your mod-installer and have it updated as well.  Any ideas?

**Comment by WulfMarius** [comment]
The update to TLD V1.41 replaced a DLL that's patched to allow modding.

You can check by looking at the version number on the main menu:
![screen_55db3e8d-2514-43d2-99cc-e06543f70ca2](https://user-images.githubusercontent.com/30952928/50471555-882ea680-09b5-11e9-89c9-124d3d93b481.png)

If "Modded" is missing, you need to repatch that DLL.  
Do this by downloading the latest version the ModLoader from here: https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/latest

**Comment by hozz1235** [comment]
Worked perfectly with those instructions - you rock!
